import { AiOutlineCloudUpload } from "react-icons/ai";
import { FaLocationArrow } from "react-icons/fa";
import { GiPerpendicularRings } from "react-icons/gi";
import { SiJetpackcompose } from "react-icons/si";

const tasks = [
  {
    id: 1,
    name: "Finish React project",
    difficulty: "hard",
    endBy: "2025-07-15T23:59:00Z",
    priority: "high",
    status: "pending",
    tags: ["react", "frontend", "deadline"],
    description: "Complete the final UI and integrate API for React dashboard",
    createdAt: "2025-07-01T10:00:00Z",
    reminder: "2025-07-14T18:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 2,
    name: "Write blog post on JavaScript",
    difficulty: "medium",
    endBy: "2025-07-10T17:00:00Z",
    priority: "medium",
    status: "completed",
    tags: ["javascript", "writing"],
    description: "Research and write a 1500-word article about ES2025 features",
    createdAt: "2025-07-02T08:30:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 3,
    name: "Update resume",
    difficulty: "easy",
    endBy: "2025-07-05T12:00:00Z",
    priority: "low",
    status: "pending",
    tags: ["career", "personal"],
    description: "Add recent projects and skills to resume",
    createdAt: "2025-07-01T12:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 4,
    name: "Prepare for interview",
    difficulty: "hard",
    endBy: "2025-07-20T09:00:00Z",
    priority: "high",
    status: "pending",
    tags: ["interview", "preparation"],
    description: "Practice algorithms and system design questions",
    createdAt: "2025-07-03T15:00:00Z",
    reminder: "2025-07-19T20:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 5,
    name: "Team meeting",
    difficulty: "easy",
    endBy: "2025-07-08T10:00:00Z",
    priority: "medium",
    status: "completed",
    tags: ["work", "meeting"],
    description: "Discuss project milestones and blockers",
    createdAt: "2025-07-04T09:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 6,
    name: "Design new logo",
    difficulty: "medium",
    endBy: "2025-07-18T23:59:00Z",
    priority: "medium",
    status: "pending",
    tags: ["design", "branding"],
    description: "Create multiple logo drafts for the new product",
    createdAt: "2025-07-06T11:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 7,
    name: "Fix login bug",
    difficulty: "hard",
    endBy: "2025-07-07T18:00:00Z",
    priority: "high",
    status: "overdue",
    tags: ["bug", "frontend"],
    description: "Resolve issue causing login failure on mobile devices",
    createdAt: "2025-06-30T14:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
];

const tasksDemo = [
  {
    id: 1,
    name: "Finish React project",
    difficulty: "hard",
    endBy: "2025-07-15T23:59:00Z",
    priority: "high",
    status: "pending",
    tags: ["react", "frontend", "deadline"],
    description: "Complete the final UI and integrate API for React dashboard",
    createdAt: "2025-07-01T10:00:00Z",
    reminder: "2025-07-14T18:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 2,
    name: "Write blog post on JavaScript",
    difficulty: "medium",
    endBy: "2025-07-10T17:00:00Z",
    priority: "medium",
    status: "completed",
    tags: ["javascript", "writing"],
    description: "Research and write a 1500-word article about ES2025 features",
    createdAt: "2025-07-02T08:30:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 3,
    name: "Update resume",
    difficulty: "easy",
    endBy: "2025-07-05T12:00:00Z",
    priority: "low",
    status: "pending",
    tags: ["career", "personal"],
    description: "Add recent projects and skills to resume",
    createdAt: "2025-07-01T12:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 4,
    name: "Prepare for interview",
    difficulty: "hard",
    endBy: "2025-07-20T09:00:00Z",
    priority: "high",
    status: "pending",
    tags: ["interview", "preparation"],
    description: "Practice algorithms and system design questions",
    createdAt: "2025-07-03T15:00:00Z",
    reminder: "2025-07-19T20:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 5,
    name: "Team meeting",
    difficulty: "easy",
    endBy: "2025-07-08T10:00:00Z",
    priority: "medium",
    status: "completed",
    tags: ["work", "meeting"],
    description: "Discuss project milestones and blockers",
    createdAt: "2025-07-04T09:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 6,
    name: "Design new logo",
    difficulty: "medium",
    endBy: "2025-07-18T23:59:00Z",
    priority: "medium",
    status: "pending",
    tags: ["design", "branding"],
    description: "Create multiple logo drafts for the new product",
    createdAt: "2025-07-06T11:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    id: 7,
    name: "Fix login bug",
    difficulty: "hard",
    endBy: "2025-07-07T18:00:00Z",
    priority: "high",
    status: "overdue",
    tags: ["bug", "frontend"],
    description: "Resolve issue causing login failure on mobile devices",
    createdAt: "2025-06-30T14:00:00Z",subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
];

const cardData = [
  {
    title: "Important Task",
    des: "High-priority subtasks to handle",
    icon: <SiJetpackcompose />,
    color: "bg-red-700",
    className: "py-10 px-8",
    subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    title: "Important Task",
    des: "High-priority subtasks to handle",
    icon: <SiJetpackcompose />,
    color: "bg-blue-800",
    className: "py-10 px-8",
    subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
  {
    title: "Important Task",
    des: "High-priority subtasks to handle",
    icon: <SiJetpackcompose />,
    color: "bg-green-700",
    className: "py-10 px-8",
    subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
];

const scheduleData = [
  {
    title: "Important Task",
    des: "High-priority subtasks to handle",
    icon: <SiJetpackcompose />,
    color: "bg-red-700",
    className: "py-4 px-5 scale-95",
    subtasks: [
      {
        name: "Tasks UI",
        des: "Complete frontend bug fixes",
        color: "#FF5733",
        date: "2024-07-07",
        completion: 50,
      },
      {
        name: "Website",
        des: "API integration task",
        color: "#3375FF",
        date: "2024-07-08",
        completion: 75,
      },
    ],
  },
];

const cardsData = [
  {
    text: "Total Tasks",
    body: "Total number of tasks today",
    icon: <SiJetpackcompose />,
    className: "min-w-[220px] max-w-xs rounded-xl p-5 backdrop-blur shadow-lg transition-colors duration-300",
    classButton: "text-[1.5em] rounded-full bg-blue-500 text-white p-3 flex items-center justify-center transition-colors duration-300 hover:bg-blue-600",
  },
  {
    text: "Pending Tasks",
    body: "Total number of pending tasks today",
    icon: <FaLocationArrow />,
    className: "min-w-[220px] max-w-xs rounded-xl p-5 backdrop-blur shadow-lg transition-colors duration-300",
    classButton: "text-[1.2em] rounded-full bg-red-500 text-white p-3 flex items-center justify-center transition-colors duration-300 hover:bg-red-600",
  },
  {
    text: "Due Tasks",
    body: "Total number of due tasks today",
    icon: <AiOutlineCloudUpload />,
    className: "min-w-[220px] max-w-xs rounded-xl p-5 backdrop-blur shadow-lg transition-colors duration-300",
    classButton: "text-[1.7em] rounded-full bg-yellow-400 text-black p-3 flex items-center justify-center transition-colors duration-300 hover:bg-yellow-500",
  },
  {
    text: "Completed Tasks",
    body: "Total number of completed tasks today",
    icon: <GiPerpendicularRings />,
    className: "min-w-[220px] max-w-xs rounded-xl p-5 backdrop-blur shadow-lg transition-colors duration-300",
    classButton: "text-[1.7em] font-semibold rounded-full bg-green-600 text-white p-3 flex items-center justify-center transition-colors duration-300 hover:bg-green-700",
  },
];

const recentCards = [
  {
    imp: 'high',
    name: 'UI Design',
    des: 'Complete the profile UI Design and code',
    tags: ['Website', 'Code', 'Design'],
  },
  {
    imp: 'med',
    name: 'API Integration',
    des: 'Integrate backend APIs for the dashboard',
    tags: ['Backend', 'API', 'Integration'],
  },
  {
    imp: 'low',
    name: 'Bug Fixes',
    des: 'Resolve minor layout and style issues',
    tags: ['Frontend', 'CSS', 'Fix'],
  },
  {
    imp: 'normal',
    name: 'Content Update',
    des: 'Update content and documentation',
    tags: ['Docs', 'Content', 'Update'],
  },
];

export { cardData, scheduleData, tasks, cardsData, recentCards, tasksDemo } 